### ISSUE TITLE
In the README, default value for `--percentage` says 0.5

### ISSUE THREAD

**Issue by Speedphoenix** [berkay-dincer/kubethanos#3]
In README.md, line 19 it says
```
--percentage // percentage of pods to kill. Default is 0.5 
```
I think this should be 50%, or, if the value of the option should be between 0 and 1, the name and description should be changed

**Comment by berkay-dincer** [comment]
I agree, does "ratio" sounds better?

**Comment by Speedphoenix** [comment]
Yes it does, that works.

**Comment by berkay-dincer** [comment]
Changed it
