### ISSUE TITLE
kubethanos deletes itself

### ISSUE THREAD

**Issue by atakanyenel** [berkay-dincer/kubethanos#5]
When deploying and running the program in dry-run, `thanoskube` shows up in the pods to be deleted. I think it should be added to `excluded-pod-names` by default.

**Comment by berkay-dincer** [comment]
Hey, I always thought you would use this in another namespace. Any specific reason why you are not running `kubethanos` in a different namespace?

**Comment by atakanyenel** [comment]
Even if you run it in a different namespace, the program might delete it when you don't exclude any namespaces ?

**Comment by berkay-dincer** [comment]
But you can only include namespaces, not exclude them. So you can always deploy kubethanos to another namespace and include a namespace different than the one you deployed to. 

I agree this might be considered a bit of a workaround but with the current design being including namespaces and excluding pods this is a bit hard to implement as getting the name of the pods kubethanos is working on not really possible. And getting the namespace kubethanos is working on is not enough to solve the problem :(
