### ISSUE TITLE
Feature request: time jump

### ISSUE THREAD

**Issue by lnguyen** [berkay-dincer/kubethanos#6]
Is it possible to add time jump feature, where half the pods come back with older version that was deleted and have been brought back with infinity stones that we stole from other timelines?

**Comment by johnlonganecker** [comment]
+1

**Comment by berkay-dincer** [comment]
Lore wise good idea but I do not think it is possible to spawn pods with older versions. Please correct me if am wrong

**Comment by lnguyen** [comment]
pretty sure you cant but that would be great if you could
